/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewReel {
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'uploader' : string,
  'videoUrl' : string,
}
export interface Reel {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'viewCount' : bigint,
  'uploader' : string,
  'videoUrl' : string,
}
export interface ViewRange { 'end' : bigint, 'start' : bigint }
export interface _SERVICE {
  'filterByTag' : ActorMethod<[string, ViewRange], Array<Reel>>,
  'getAllReels' : ActorMethod<[], Array<Reel>>,
  'getFeaturedReels' : ActorMethod<[ViewRange], Array<Reel>>,
  'getReel' : ActorMethod<[bigint], Reel>,
  'incrementViewCount' : ActorMethod<[bigint], boolean>,
  'submitReel' : ActorMethod<[NewReel], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];