/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ViewRange = IDL.Record({ 'end' : IDL.Nat, 'start' : IDL.Nat });
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'uploader' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const NewReel = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'uploader' : IDL.Text,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterByTag' : IDL.Func([IDL.Text, ViewRange], [IDL.Vec(Reel)], ['query']),
  'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getFeaturedReels' : IDL.Func([ViewRange], [IDL.Vec(Reel)], ['query']),
  'getReel' : IDL.Func([IDL.Nat], [Reel], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitReel' : IDL.Func([NewReel], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ViewRange = IDL.Record({ 'end' : IDL.Nat, 'start' : IDL.Nat });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'uploader' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const NewReel = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'uploader' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'filterByTag' : IDL.Func([IDL.Text, ViewRange], [IDL.Vec(Reel)], ['query']),
    'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getFeaturedReels' : IDL.Func([ViewRange], [IDL.Vec(Reel)], ['query']),
    'getReel' : IDL.Func([IDL.Nat], [Reel], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitReel' : IDL.Func([NewReel], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };